### ISSUE TITLE
With some mods on SCRAP it shows an inaccurate number of things in the complex

### ISSUE THREAD

**Issue by Paradox75831004** [fivetoofive/LethalCompany-DetailedScan#3]
Sometimes with a regular “scan” it shows the correct number of things, but with a “detailed” scan only part of it is shown (in some cases it shows + - the correct quantity)
![laz2ooeZ3eg](https://github.com/fivetoofive/LethalCompany-DetailedScan/assets/72872478/0921dc7d-f226-40db-ac4d-506f45ae9a5d)

**Comment by Paradox75831004** [comment]
![image](https://github.com/fivetoofive/LethalCompany-DetailedScan/assets/72872478/6363d8da-3d36-412a-b45c-c35c2f6fcd1f)
![image](https://github.com/fivetoofive/LethalCompany-DetailedScan/assets/72872478/a8683a61-0b83-48f0-84e4-44fb56362e1f)

**Comment by Paradox75831004** [comment]
Or here on Exp
![image](https://github.com/fivetoofive/LethalCompany-DetailedScan/assets/72872478/36057328-d103-4995-a55f-63b4ce56ebbf)
![image](https://github.com/fivetoofive/LethalCompany-DetailedScan/assets/72872478/8261caac-6bfc-41b8-87d9-9f3f0af7e132)

**Comment by fivetoofive** [comment]
Hey, sorry for the late response. I checked each of the mods that you have listed and all of them work on my end and are being listed by DetailedScan. So I have been unable to replicate the issue you are having. I just fixed a mod breaking bug though when looking into this issue, so that may have been the cause of this problem. If the problem still persists, let me know.
