### ISSUE TITLE
Seems to have died in v47

### ISSUE THREAD

**Issue by VaelophisNyx** [fivetoofive/LethalCompany-DetailedScan#5]
Understandable since the update just dropped and all, just bringing it up here

**Comment by fivetoofive** [comment]
Hey, I haven't been able to find any problems with the mod for the new update. What is the type of problem you are experiencing?

**Comment by VaelophisNyx** [comment]
it was just returning [scanforitems] when Scan was ran

**Comment by fivetoofive** [comment]
After looking into it some more, this issue seems to be a bug with the game itself, and not the mod. The [scanforitems] prompt appears for both the unmodified built-in scan and the modded detailed scan at the same time during cases that it takes place. It only seems to effect a few edge cases and will probably be fixed in the future, so I'm going to stop looking into it for now. Thanks for the heads up.

**Comment by VaelophisNyx** [comment]
aha, that'd explain that
